controller_manager:
  ros_parameters:
    update_rate: 100 # Hz

cartesian_motion_controller:
  type: cartesian_motion_controller/CartesianMotionController
  
  ros_parameters:
    robot_description: robot_description
    robot_base_link: silvestrobase_link
    end_effector_link: "tool0"


    joints:
      - silvestroshoulder_pan_joint
      - silvestroshoulder_lift_joint
      - silvestroelbow_joint
      - silvestrowrist_1_joint
      - silvestrowrist_2_joint
      - silvestrowrist_3_joint

    command_interface: 
      #- position
      - velocity

    ik_solver: "selectively_damped_least_squares"
   
    solver:
      error_scale: 1.0 # Scale the error for the solver, influence how fast the controller converges, high values mean faster convergence but can lead to instability
      iterations: 1 # Number of iterations for the solver, higher values can lead to more accurate solutions but increase computation time
      publish_state_feedback: true # Publish the state feedback to the controller manager, useful for debugging and monitoring 